spring.application.name=ssl-analyzer
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8080
spring.thymeleaf.cache=false
# cd "C:\Users\hp\Downloads\ssl-analyzer (1)\ssl-analyzer"
# docker-compose up --build
# docker-compose up -d

#docker-compose down